# Project
version=1.0.0
group=johnsmith.enchantmentcore
java_version=21

# Minecraft
minecraft_version=1.21
minecraft_version_supremum=1.21.1
minecraft_version_upper_limit=1.21.2

# Common
mod_id=enchantment_core
mod_name=Enchantment Core
mod_name_normalized=enchantment-core
mod_author=JohnSmith474
license=Custom (All Rights Reserved)
credits=
description=Enchantment Core is a data-driven library framework facilitating dynamic enchantment configuration and volumetric spell field execution.\
\n\
\n\
\n\Key Features:\
\n- Component Library:\
\n\     Access an extensive suite of pre-defined enchantment effects, volumetric shapes, and target evaluators.\
\n\
\n- Modular Spell Fields:\
\n\     Execute volume-based entity, block, and visual effects using bounded spatial geometries and topological falloff algorithms.\
\n\
\n- Configuration Integration:\
\n\     Bridge vanilla JSON definitions with dynamic configuration backends utilizing custom map codecs.\
\n\
\n- Data Transformation Pipeline:\
\n\     Import and export static enchantment parameters into configurable runtime structures.\
\n\
\n- Mathematical Value Codecs:\
\n\     Implement non-linear polynomial and diminishing returns functions within the LevelBasedValue ecosystem.

# Dependencies
neo_form_version=1.21-20240613.152323
parchment_minecraft=1.21
parchment_version=2024.06.23

# Fabric
fabric_version=0.100.8+1.21
fabric_loader_version=0.16.9

# Forge
forge_version=51.0.30
forge_loader_version_range=[51,)

# NeoForge
neoforge_version=21.0.167
neoforge_loader_version_range=[4,)

# Config Overhauled
config_overhauled_project_id=9sKFMO62
config_overhauled_project_name=config-overhauled
config_overhauled_version=1.0.1
config_overhauled_version_upper_limit=2.0.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true